---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-webhook-token-secret
    template:
      data:
        token: "{{ .FLUX_GITHUB_WEBHOOK_TOKEN }}"
  dataFrom:
    - extract:
        key: flux
# ---  # darg-ops-change
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json  # darg-ops-change
# apiVersion: external-secrets.io/v1  # darg-ops-change
# kind: ExternalSecret  # darg-ops-change
# metadata:  # darg-ops-change
#   name: sops-age  # darg-ops-change
# spec:  # darg-ops-change
#   secretStoreRef:  # darg-ops-change
#     kind: ClusterSecretStore  # darg-ops-change
#     name: onepassword  # darg-ops-change
#   target:  # darg-ops-change
#     name: sops-age-secret  # darg-ops-change
#     template:  # darg-ops-change
#       data:  # darg-ops-change
#         age.agekey: "{{ .SOPS_PRIVATE_KEY }}"  # darg-ops-change
#   dataFrom:  # darg-ops-change
#     - extract:  # darg-ops-change
#         key: sops  # darg-ops-change
