---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-status-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gitlab-status-token-secret
    template:
      data:
        token: "{{ .FLUX_GITLAB_TOKEN }}"
  dataFrom:
    - extract:
        key: flux
