---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: gitlab-status
spec:
  type: gitlab
  address: https://gitlab.com/ki3lich/darg-home-ops
  secretRef:
    name: gitlab-status-token-secret
