---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: go2rtc-config-secret
    template:
      data:
        go2rtc.yaml: |
          ---
          api:
            listen: :80
          rtsp:
            listen: :554
          webrtc:
            listen: :8555
            candidates:
              - 192.168.42.124:8555
              - stun:8555
            ice_servers:
              - urls:
                  - stun:stun.cloudflare.com:3478
          streams:
            tbr1:
              - rtsp://{{ .username }}:{{ .password }}@192.168.1.234:80/Streaming/Channels/101
  dataFrom:
    - extract:
        key: dvr
