---
originRequest:
  originServerName: external.darg.win

ingress:
  - hostname: darg.win
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.darg.win"
    service: *svc
  - service: http_status:404
